// Dominio/TabelaTerritorialAIS.js
// Tabela canônica territorial de Áreas Integradas de Segurança (AIS) de Pernambuco
// Fontes oficiais:
// - Portaria SDS nº 1197 de 11/06/2010 (DOE 15/06/2010)
// - Lei Estadual nº 14.320/2011 (Anexo Único, alterada pela Lei nº 14.890/2012)
// - Portaria SDS nº 129/2008 e Decreto Estadual nº 26.868/2004

var TABELA_TERRITORIAL_AIS = {
  "meta": {
    "versao": "1.0.0",
    "dataPublicacao": "2026-09-04",
    "fontesOficiais": [
      "Portaria SDS nº 1197 de 11/06/2010 (DOE 15/06/2010)",
      "Lei Estadual nº 14.320/2011 (Anexo Único, alterada pela Lei nº 14.890/2012)",
      "Portaria SDS nº 129/2008",
      "Decreto Estadual nº 26.868/2004"
    ],
    "descricao": "Tabela canônica territorial de Áreas Integradas de Segurança (AIS) de Pernambuco."
  },
  "municipiosMultiAis": {
    "RECIFE": {
      "aisPadrao": null,
      "bairros": {
        "BOA VISTA": "AIS 1",
        "CABANGA": "AIS 1",
        "COELHOS": "AIS 1",
        "ILHA DO LEITE": "AIS 1",
        "ILHA JOANA BEZERRA": "AIS 1",
        "PAISSANDU": "AIS 1",
        "RECIFE": "AIS 1",
        "BAIRRO DO RECIFE": "AIS 1",
        "RECIFE ANTIGO": "AIS 1",
        "SANTO AMARO": "AIS 1",
        "SANTO ANTONIO": "AIS 1",
        "SAO JOSE": "AIS 1",
        "SOLEDADE": "AIS 1",
        "AGUA FRIA": "AIS 2",
        "ALTO DO PASCOAL": "AIS 2",
        "ARRUDA": "AIS 2",
        "CAJUEIRO": "AIS 2",
        "CAMPINA DO BARRETO": "AIS 2",
        "CAMPO GRANDE": "AIS 2",
        "CHAO DE ESTRELAS": "AIS 2",
        "CORDEIRO": "AIS 2",
        "DERBY": "AIS 2",
        "ENCRUZILHADA": "AIS 2",
        "ESPINHEIRO": "AIS 2",
        "FUNDAO": "AIS 2",
        "GRACAS": "AIS 2",
        "HIPODROMO": "AIS 2",
        "IPUTINGA": "AIS 2",
        "MADALENA": "AIS 2",
        "PONTO DE PARADA": "AIS 2",
        "ROSARINHO": "AIS 2",
        "TORRE": "AIS 2",
        "TORREAO": "AIS 2",
        "ZUMBI": "AIS 2",
        "BOA VIAGEM": "AIS 3",
        "BRASILIA TEIMOSA": "AIS 3",
        "IMBIRIBEIRA": "AIS 3",
        "IPSEP": "AIS 3",
        "JORDAO": "AIS 3",
        "PINA": "AIS 3",
        "SETUBAL": "AIS 3",
        "AFOGADOS": "AIS 4",
        "AREIAS": "AIS 4",
        "BARRO": "AIS 4",
        "BONGI": "AIS 4",
        "CACOTE": "AIS 4",
        "CAXANGA": "AIS 4",
        "CIDADE UNIVERSITARIA": "AIS 4",
        "COQUEIRAL": "AIS 4",
        "CURADO": "AIS 4",
        "ENGENHO DO MEIO": "AIS 4",
        "ESTANCIA": "AIS 4",
        "ILHA DO RETIRO": "AIS 4",
        "JARDIM SAO PAULO": "AIS 4",
        "JIQUIA": "AIS 4",
        "MANGUEIRA": "AIS 4",
        "MUSTARDINHA": "AIS 4",
        "PRADO": "AIS 4",
        "SANCHO": "AIS 4",
        "SAN MARTIN": "AIS 4",
        "TEJIPIO": "AIS 4",
        "TORROES": "AIS 4",
        "TOTO": "AIS 4",
        "VARZEA": "AIS 4",
        "ALTO DA BELA VISTA": "AIS 5",
        "ALTO DO MANDU": "AIS 5",
        "ALTO DO REFUGIO": "AIS 5",
        "ALTO JOSE BONIFACIO": "AIS 5",
        "ALTO JOSE DO PINHO": "AIS 5",
        "ALTO SANTA TEREZINHA": "AIS 5",
        "APIPUCOS": "AIS 5",
        "BEBERIBE": "AIS 5",
        "BOMBA DO HEMETERIO": "AIS 5",
        "BREJO DA GUABIRABA": "AIS 5",
        "BREJO DE BEBERIBE": "AIS 5",
        "CASA AMARELA": "AIS 5",
        "CASA FORTE": "AIS 5",
        "CORREGO DO JENIPAPO": "AIS 5",
        "DOIS IRMAOS": "AIS 5",
        "DOIS UNIDOS": "AIS 5",
        "GUABIRABA": "AIS 5",
        "JAQUEIRA": "AIS 5",
        "LINHA DO TIRO": "AIS 5",
        "MACAXEIRA": "AIS 5",
        "MANGABEIRA": "AIS 5",
        "MONTEIRO": "AIS 5",
        "MORRO DA CONCEICAO": "AIS 5",
        "NOVA DESCOBERTA": "AIS 5",
        "PARNAMIRIM": "AIS 5",
        "PASSARINHO": "AIS 5",
        "PAU FERRO": "AIS 5",
        "POCO DA PANELA": "AIS 5",
        "PORTO DA MADEIRA": "AIS 5",
        "SANTANA": "AIS 5",
        "SITIO DOS PINTOS": "AIS 5",
        "TAMARINEIRA": "AIS 5",
        "VASCO DA GAMA": "AIS 5"
      }
    }
  },
  "municipiosMonoAis": {
    "JABOATAO DOS GUARARAPES": "AIS 6",
    "JABOATAO": "AIS 6",
    "MORENO": "AIS 6",
    "OLINDA": "AIS 7",
    "PAULISTA": "AIS 8",
    "ABREU E LIMA": "AIS 8",
    "IGARASSU": "AIS 8",
    "ITAPISSUMA": "AIS 8",
    "ILHA DE ITAMARACA": "AIS 8",
    "ITAMARACA": "AIS 8",
    "ARACOIABA": "AIS 8",
    "CAMARAGIBE": "AIS 9",
    "SAO LOURENCO DA MATA": "AIS 9",
    "CABO DE SANTO AGOSTINHO": "AIS 10",
    "IPOJUCA": "AIS 10",
    "GOIANA": "AIS 11",
    "ALIANCA": "AIS 11",
    "CAMUTANGA": "AIS 11",
    "CONDADO": "AIS 11",
    "FERREIROS": "AIS 11",
    "ITAMBE": "AIS 11",
    "ITAQUITINGA": "AIS 11",
    "MACAPARANA": "AIS 11",
    "SAO VICENTE FERRER": "AIS 11",
    "TIMBAUBA": "AIS 11",
    "VITORIA DE SANTO ANTAO": "AIS 12",
    "AMARAJI": "AIS 12",
    "CHÃ DE ALEGRIA": "AIS 12",
    "CHA DE ALEGRIA": "AIS 12",
    "CHÃ GRANDE": "AIS 12",
    "CHA GRANDE": "AIS 12",
    "ESCADA": "AIS 12",
    "GLORIA DO GOITA": "AIS 12",
    "POMBOS": "AIS 12",
    "PRIMAVERA": "AIS 12",
    "PALMARES": "AIS 13",
    "AGUA PRETA": "AIS 13",
    "BARREIROS": "AIS 13",
    "BELEM DE MARIA": "AIS 13",
    "CATENDE": "AIS 13",
    "CORTES": "AIS 13",
    "GAMELEIRA": "AIS 13",
    "JAQUEIRA": "AIS 13",
    "JOAQUIM NABUCO": "AIS 13",
    "MARAIAL": "AIS 13",
    "QUIPAPA": "AIS 13",
    "RIBEIRAO": "AIS 13",
    "RIO FORMOSO": "AIS 13",
    "SAO BENEDITO DO SUL": "AIS 13",
    "SAO JOSE DA COROA GRANDE": "AIS 13",
    "SIRINHAEM": "AIS 13",
    "TAMANDARE": "AIS 13",
    "XEXEU": "AIS 13",
    "CARUARU": "AIS 14",
    "ALTINHO": "AIS 14",
    "AGRESTINA": "AIS 14",
    "BONITO": "AIS 14",
    "CAMOCIM DE SAO FELIX": "AIS 14",
    "CUPIRA": "AIS 14",
    "IBIRAJUBA": "AIS 14",
    "JUREMA": "AIS 14",
    "PANELAS": "AIS 14",
    "RIACHO DAS ALMAS": "AIS 14",
    "SAIRÉ": "AIS 14",
    "SAIRE": "AIS 14",
    "BELO JARDIM": "AIS 15",
    "BENTO ALBUQUERQUE": "AIS 15",
    "BEZERROS": "AIS 15",
    "BREJO DA MADRE DE DEUS": "AIS 15",
    "CACHOEIRINHA": "AIS 15",
    "GRAVATA": "AIS 15",
    "PESQUEIRA": "AIS 15",
    "POÇÃO": "AIS 15",
    "POCAO": "AIS 15",
    "SANHARO": "AIS 15",
    "SAO BENTO DO UNA": "AIS 15",
    "SAO CAETANO": "AIS 15",
    "TACAIMBO": "AIS 15",
    "LIMOEIRO": "AIS 16",
    "BOM JARDIM": "AIS 16",
    "BUENOS AIRES": "AIS 16",
    "CARPINA": "AIS 16",
    "CASINHAS": "AIS 16",
    "CUMARU": "AIS 16",
    "FEIRA NOVA": "AIS 16",
    "JOAO ALFREDO": "AIS 16",
    "LAGOA DO CARRO": "AIS 16",
    "LAGOA DE ITAENGA": "AIS 16",
    "MACHADOS": "AIS 16",
    "NAZARE DA MATA": "AIS 16",
    "OROBÓ": "AIS 16",
    "OROBO": "AIS 16",
    "PASSIRA": "AIS 16",
    "PAUDALHO": "AIS 16",
    "SALGADINHO": "AIS 16",
    "SURUBIM": "AIS 16",
    "TRACUNHAEM": "AIS 16",
    "VERTENTE DO LERIO": "AIS 16",
    "VICENCIA": "AIS 16",
    "SANTA CRUZ DO CAPIBARIBE": "AIS 17",
    "FREI MIGUELINHO": "AIS 17",
    "JATAUBA": "AIS 17",
    "SANTA MARIA DO CAMBUCA": "AIS 17",
    "TAQUARITINGA DO NORTE": "AIS 17",
    "TORITAMA": "AIS 17",
    "VERTENTES": "AIS 17",
    "GARANHUNS": "AIS 18",
    "AGUAS BELAS": "AIS 18",
    "ANGELIM": "AIS 18",
    "BOM CONSELHO": "AIS 18",
    "BREJAO": "AIS 18",
    "CAETÉS": "AIS 18",
    "CAETES": "AIS 18",
    "CALCADO": "AIS 18",
    "CANHOTINHO": "AIS 18",
    "CAPOEIRAS": "AIS 18",
    "CORRENTES": "AIS 18",
    "IATI": "AIS 18",
    "ITAITINGA": "AIS 18",
    "JUCATI": "AIS 18",
    "JUPI": "AIS 18",
    "LAGOINHA": "AIS 18",
    "LAJEDO": "AIS 18",
    "PALMEIRINA": "AIS 18",
    "PARANATAMA": "AIS 18",
    "SALOA": "AIS 18",
    "SAO JOAO": "AIS 18",
    "TEREZINHA": "AIS 18",
    "ARCOVERDE": "AIS 19",
    "ALAGOINHA": "AIS 19",
    "BUIQUE": "AIS 19",
    "CUSTODIA": "AIS 19",
    "IBIMIRIM": "AIS 19",
    "INAJA": "AIS 19",
    "MANARI": "AIS 19",
    "PEDRA": "AIS 19",
    "SERTANIA": "AIS 19",
    "TUPANATINGA": "AIS 19",
    "VENTUROSA": "AIS 19",
    "AFOGADOS DA INGAZEIRA": "AIS 20",
    "BREJINHO": "AIS 20",
    "CALUMBI": "AIS 20",
    "CARNAIBA": "AIS 20",
    "FLORES": "AIS 20",
    "IGUARACY": "AIS 20",
    "INGAZEIRA": "AIS 20",
    "ITAPETIM": "AIS 20",
    "QUIXABA": "AIS 20",
    "SANTA CRUZ DA BAIXA VERDE": "AIS 20",
    "SANTA TEREZINHA": "AIS 20",
    "SAO JOSE DO EGITO": "AIS 20",
    "SERRA TALHADA": "AIS 20",
    "SOLIDÃO": "AIS 20",
    "SOLIDAO": "AIS 20",
    "TABIRA": "AIS 20",
    "TRIUNFO": "AIS 20",
    "TUPARETAMA": "AIS 20",
    "FLORESTA": "AIS 21",
    "BELEM DO SAO FRANCISCO": "AIS 21",
    "BETANIA": "AIS 21",
    "CARNAUBEIRA DA PENHA": "AIS 21",
    "ITACURUBA": "AIS 21",
    "JATOBA": "AIS 21",
    "PETROLANDIA": "AIS 21",
    "TACARATU": "AIS 21",
    "SALGUEIRO": "AIS 22",
    "CEDRO": "AIS 22",
    "MIRANDIBA": "AIS 22",
    "PARNAMIRIM": "AIS 22",
    "SAO JOSE DO BELMONTE": "AIS 22",
    "SERRITA": "AIS 22",
    "VERDEJANTE": "AIS 22",
    "OURICURI": "AIS 23",
    "ARARIPINA": "AIS 23",
    "BODOCO": "AIS 23",
    "EXU": "AIS 23",
    "GRANITO": "AIS 23",
    "IPUBI": "AIS 23",
    "MOREILANDIA": "AIS 23",
    "SANTA CRUZ": "AIS 23",
    "SANTA FILOMENA": "AIS 23",
    "TRINDADE": "AIS 23",
    "CABROBO": "AIS 25",
    "OROCO": "AIS 25",
    "SANTA MARIA DA BOA VISTA": "AIS 25",
    "PETROLINA": "AIS 26",
    "AFRANIO": "AIS 26",
    "DORMENTES": "AIS 26",
    "LAGOA GRANDE": "AIS 26",
    "FERNANDO DE NORONHA": "AIS ESPECIAL"
  },
  "bairrosMonoAisConhecidos": {
    "PIEDADE": "AIS 6",
    "CANDEIAS": "AIS 6",
    "BARRA DE JANGADA": "AIS 6",
    "PRAZERES": "AIS 6",
    "CAVALEIRO": "AIS 6",
    "JABOATAO CENTRO": "AIS 6",
    "MURIBECA": "AIS 6",
    "CURCURANA": "AIS 6",
    "ZUMBI DO PACHECO": "AIS 6",
    "SUCUPIRA": "AIS 6",
    "JARDIM JORDAO": "AIS 6",
    "BAIRRO NOVO": "AIS 7",
    "CASA CAIADA": "AIS 7",
    "RIO DOCE": "AIS 7",
    "PEIXINHOS": "AIS 7",
    "JARDIM ATLANTICO": "AIS 7",
    "VARADOURO": "AIS 7",
    "AMPARO": "AIS 7",
    "FRAGOSO": "AIS 7",
    "CIDADE TABAJARA": "AIS 7",
    "OURO PRETO": "AIS 7",
    "JANGA": "AIS 8",
    "MARANGUAPE I": "AIS 8",
    "MARANGUAPE II": "AIS 8",
    "PAU AMARELO": "AIS 8",
    "ARTHUR LUNDGREN": "AIS 8",
    "NOBRE": "AIS 8",
    "CONCEICAO": "AIS 8",
    "SANTA MONICA": "AIS 9",
    "TABATINGA": "AIS 9",
    "ALBERTO MAIA": "AIS 9",
    "ALDEIA": "AIS 9",
    "CEU AZUL": "AIS 9",
    "VILA DA FABRICA": "AIS 9",
    "TIMBI": "AIS 9",
    "PONTE DOS CARVALHOS": "AIS 10",
    "PONTEZINHA": "AIS 10",
    "GAIBU": "AIS 10",
    "ENSEADA DOS CORAIS": "AIS 10",
    "SUAPE": "AIS 10",
    "PORTO DE GALINHAS": "AIS 10",
    "NOSSA SENHORA DO O": "AIS 10",
    "CAMELA": "AIS 10",
    "SERRAMBI": "AIS 10"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    TABELA_TERRITORIAL_AIS: TABELA_TERRITORIAL_AIS
  };
}
